# Generated by Django 5.2.3 on 2025-06-29 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uitgevoerde_werkzaamheden",
                    models.TextField(
                        help_text="Gedetailleerde omschrijving van de uitgevoerde werkzaamheden."
                    ),
                ),
                (
                    "gebruikte_materialen",
                    models.TextField(
                        blank=True,
                        help_text="Lijst van gebruikte materialen en onderdelen.",
                        null=True,
                    ),
                ),
                (
                    "opmerkingen_bevindingen",
                    models.TextField(
                        blank=True,
                        help_text="Eventuele opmerkingen, bevindingen of aanbevelingen.",
                        null=True,
                    ),
                ),
                (
                    "asset_status_na_onderhoud",
                    models.CharField(
                        blank=True,
                        help_text="Status van de asset na het onderhoud (bijv. 'In bedrijf', 'Vereist opvolging', 'Buiten bedrijf').",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "werktijd_minuten",
                    models.PositiveIntegerField(
                        blank=True, help_text="Totale werktijd in minuten.", null=True
                    ),
                ),
                (
                    "datum_opgesteld",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datum en tijd waarop het rapport is aangemaakt/opgesteld.",
                    ),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("gewijzigd_op", models.DateTimeField(auto_now=True)),
                (
                    "gebruiker_opsteller",
                    models.ForeignKey(
                        blank=True,
                        help_text="Monteur/inspecteur die het rapport heeft opgesteld.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "onderhoudstaak",
                    models.OneToOneField(
                        help_text="De onderhoudstaak waar dit rapport bij hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="api.maintenancetask",
                    ),
                ),
            ],
        ),
    ]
